" === Cherry-picked from defaults.vim ===
"set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands

" Show a few lines of context around the cursor.  Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

" Enable file type detection.
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
" Also load indent files, to automatically do language-dependent indenting.
" Revert with ":filetype off".
filetype plugin indent on

" Switch syntax highlighting on when the terminal has colors or when using the
" GUI (which always has colors).
if &t_Co > 2 || has("gui_running")
  " Revert with ":syntax off".
  syntax on

  " I like highlighting strings inside C comments.
  " Revert with ":unlet c_comment_strings".
  let c_comment_strings=1
endif
" === End defaults.vim section ===

set ai " Auto indenting on
set tabstop=4 " Decrease width of tabs
set shiftwidth=4 " Indentation depth (pads tabs with spaces if greater than tabstop)
"set noexpandtab " Always use tabs for indenting

set rnu " Show relative line numbers
set showbreak=> " Indicate when a line wraps
"set noexpandtab " Always use tabs

set belloff=all " Silence dinging

" Move up/down by display lines so text wrapping is seamless
map <up> gk
map <down> gj

" Creates a vertical split with a terminal on the right side
command! Vterm :botright vert term
cnoreabbrev vt :Vterm
nnoremap <F3> :Vterm<CR>

" Sometimes I hold Shift for slightly too long after pressing Colon
command! W :w
command! WQ :wq
command! Wq :wq

" Highlight all instances of a search, until the search is closed
:set hlsearch
:nnoremap <CR> :nohlsearch<CR><CR>

