# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/be2af937-eeb5-4b79-8132-3b74cc0145f2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8C26-5DE1";
      fsType = "vfat";
    };

  fileSystems."/run/media/kaizen/Nautilus" =
    { device = "/dev/disk/by-label/Nautilus";
      fsType = "ext4";
      options = [
        "users" # Allow any user to mount/unmount
        "nofail" # Don't enter Emergency Mode if this drive is missing
      ];
    };

  fileSystems."/run/media/kaizen/Cuttlefish" =
    { device = "/dev/disk/by-label/Cuttlefish";
      fsType = "ext4";
      options = [
        "users" # Allow any user to mount/unmount
        "nofail" # Don't enter Emergency Mode if this drive is missing
      ];
    };

  # This system has 64GB of RAM, so adding swap isn't really useful.
  # If we run out of memory, just let the OOM reaper do its job lol
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
